spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_purchase_database
    username: alpha_user
    password: alpha_password
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        web: DEBUG